Supplies were difficult to come by, and the supplies brought on board at the beginning of the cruise were not always high quality, so even those brought from the United States sometimes had to be replaced when ships were still in the Mediterranean. Sometimes ships sailed without adequate provision of naval stores such as cord (see [Samuel Barron](), BW1:632).

- BW2:11-12: [Alexander Murray]() complains to the Secretary of the Navy about the rations based on his observations during his previous cruise
    - Beef: Poor quality and insufficient quantity (British navy does better)
    - Pork: "sufficient"
    - Fish: excluded per regulations
    - Potatoes and onions and other vegetables: ought to be allowed to be purchased locally
    - Desired: "Kiln dry'd Indian Meal" with Molasses (for breakfast)
    - "A soldier may have his resources, but the sailor hath no subterfuge when pinched"?
- BW2:17: [Alexander Murray]() is really concerned about supplies: he states that provisions run out quickly once ships reach the Med, and therefore he's not taking a full ration of everything since he's going to have to refill supplies in the Med anyway.
- BW2:73: "You must be frugal, in all your demands," writes [Richard Dale]() to [John Shaw]() in regards to taking stores from the store ship at Gibraltar, 2 March 1802
- BW2:136: "I am told [bread] ought to be baked over a second time. - Great complaints have been made in the Navy respecting bread. I pray you let there be no cause of Complaint, in that which you ship" (SecNav to [John Stricker](), naval agent, 27 April 1802)
- BW2:242: [Alexander Murray]() writes to [Richard Valentine Morris]() that he has taken only a temporary supply of provisions at Malta, as they are expensive and hard to get, and will get more supplies later at Leghorn, 20 August 1802
- BW2:315: [Alexander Murray](), having sprung his main and topmast on the route from Toulon to Gibraltar, ran out of supplies and had to stop in at Malaga in order to get repairs and acquire supplies, writing to [William Kirkpatrick](): "We have not one ounce of bread on board & beg you will send me off about 1000 lb. for present use" (19 November 1802)
- BW3:59: [Edward Preble]() writes, "It is absolutely necessary that every Article which composes our ration's should be sent out from the United States as they cannot, in consequence of the War between England and France be purchased at Gibralter and even if they could the prices at present are 50 pr Cent higher than in time of peace; Candles and Molasses have heretofore been much wanted by the other squadron, they are articles that cannot be procured, on any terms in this Country" (18 September 1803)
- BW3:164: [James Simpson]() informs [Edward Preble]() that some of the more delicacy items he might like are not available: "There has not been any Partridges for sale since you left this, the Rainy Weather has prevented any being caught, besides these Birds after tasteing the young grass will not eat dry seed so as to feed upon it - I shall now hourly expect the Nautilus, by her you will receive the Cabbags and Pumpkins you desired - I should have told you that no supplies of any sort can be sent from hence on trading Vessels for Ships of war" (25 October 1803)
- M148: 5 January 1805: Purser [Charles Wadsworth]() writes about the provisions deposited at Malta: "a quantity of Cheese and bread read by her had no mark whatever on the Cask nor did the general Invoice throw any light on it. The cheese rec'd here by the John Adams was all spoil'd before it was landed immediately after which it was [illegible] by order of Commodore Barron and the whole of it condemn'd. the cheese which I rec'd from the last Store Ship was at least two thirds of it rotten --would it not be much better to purchase Cheese and vinegar in the Mediterranean as they may be wanted; than to ship them from the United States. --- Dutch Cheese I believe may be purchased at Malta much cheaper than American cheese can be ship'd from the United States, including freight and the great probability of its rotting---Vinegar can be purchased in these Seas much better and I believe for less than the freight of that ship'd from America---The candles read by the John Adams are all unfit for use being run together, having been melted by the heat of the hold indeed all the Candles we get from the United States are very soft and bad, In consequence of which I am certain that more than double the quantity are used -- would it not be a piece of economy to send out wax Candles or wax & tallow half of each. ([Charles Wadsworth]() to [Thomas Turner](), accountant of the navy)