- Secretary of the Navy cautions naval vessels against breaking jurisdiction: " You are to refrain from exercising the powers of capturing or recapturing in waters within the Jurisdictional limits and under the protection of any other nation, in order that their peace & sovereignty may remain unviolated, and we shall scrupulously and without indulgence examine that conduct which shall bring us into collision with any other power" (BW2:60, 18 February 1802)
- [James Simpson]() invokes the law of nations when denying the request of the emperor of Morocco to allow his ships of wheat to go to Tripoli (BW2:165), around 1 June 1802
- When the United States takes a Yerban ship bound for Tripoli, the bey of Tunis is very grumpy about it. [William Eaton]() tells him that the ship should have known of the blockade and of the Americans' right to detain any ships going into Tripoli. "If, in contempt of this advice and caution, they chuse to risk their property, and it falls into our hands, it becomes, of course, good prize, by a right founded on the known and received laws of nations, applicable in such cases.'[The bey replies:] 'We Barbary States, do not admit the laws of war, established among Christian nations, applicable to us." (BW2:345, 26 January 1803) 
    - Eaton complains against the vagaries of Barbary law: "If the Barbary Regencies have customs or maxims of war peculiar to themselves, and distinct from the general and acknoledged laws of other belligerent powers, this is no reason why we should renounce the latter, and conform ourselves to the former, which indeed, are neither specified nor known, and dictated chiefly by the circumstances of the moment; even though we may find precedent for such a concession."
    - *Contrast or continuity with national laws?* Eaton continues: "It is incumbent on me at the same time to signify to you, that though I am not informed what may be the discretionary power of the Commodore in like cases, I doubt whether he be authorized to render this cargo to your claim; because, it being admitted that it was destined for Tripoli, and it being known that this port was in a state of blockade, it has become good prize to the captors, the property totally alienated from the shippers, and subject to the disposition of our laws. No decision therefore can be had in favor of the claimants without the interference of the government of the United States. But, should they consent to grant an indemnity in this case it would be an act of special favor, not of right. I hope your excellency will allow me sufficient time to submit the necessary statement to the President, my master, and wait his decision"
    - [Richard Valentine Morris]() goes to the court of the bey in order to ameliorate the problem of the captured ship, where once again differing law codes cause problems: "The Bashaw proceeded to demand that the Validity of the capture should be verified at Tunis. The Commodore persisted in his intention to send the Prize to Gibraltar to be tried by a regular Court of Admiralty, and promised to abide by their decision" (BW2:352, 27 February 1803)
- BW2:428: [Nicholas Nissen]() invokes the law of nations to demand protection for his consular boat going out to the American squadron off Tripoli (29 May 1803)
- 21 March 1803: [Albert Gallatin]() writes of a conversation with [Alexander Murray]() about passports for Moroccan grain ships: "The refusal of a passport to the Morocco provision ship he considers as ridiculous; as it could not affect the state of affairs in relation to Tripoli, and those uncivilized States cannot understand the refined theory of the law of nations & of the duties of neutrals" (TJ, http://rotunda.upress.virginia.edu/founders/TSJN-01-40-02-0074 [accessed 25 Oct 2016]) 
- BW2:443-44: SecNav's orders to [Richard Somers]() about lawful prize
- BW2:475: SecNav stresses to [Edward Preble]() the importance of not taking unlawful prize: "Your Commission extending on1 to the capture of vessels, Goods & Effects belonging to the Bey of Tripoli or to his subjects, you will bear in mind that the rights of all other nations are to be duly respected: that we are at peace and wish to continue at peace with them, and that an Amencan Commander ought to be as much distinguished for his attention and adherence to all the rights of other nations as for his firmness in support of the honor of his own country. - You are to refrain from exercising the powers of capturing or recapturing in waters within the jurisdictional limits and under the protection of any other nation. We shall scrupulously and without indulgence examine that conduct which shall bring us into collision with any other Power"
- BW2:505: [Edward Preble]() asks: "Whether the rights of other nations (than Tripoli) are to be considered as extending to their entering the harbour of Tripoli when closely blockaded" -[SecNav replies:] 'I have only to observe, that the besieging party has a right to prohibit entirely all commerce with a besieged Town. If we lay siege to a place or only form the blockade, we have a right to prevent any one from entering the place blockaded, and to treat as an enemy whoever attemps to enter the place or carry any thing to the besieged without our leave' (3 August 1803)
- BW3:116: [James Simpson]() makes some arguments for restoring the [*Meshouda*]() to the emperor, but then: "These are arguments for the Ship's being restored; but however by no means conclusive. So it may be argued that the occasional suspension of the blockade of Tripoly takes away that consequence stamp'd on regularly maintained blockades by the Law of Nations, and the Declarations of the chief powers of Europe on that subject, in the year 1780." --Is he suggesting that Morris's dereliction has made the *Meshouda* unlawful prize? Not sure. (8 October 1803)
- 

## Secondary sources on int'l law
- Arguing that the American conception of the Law of Nations included many works, some of which were contradictory: "Instead, Jefferson’s long disquisition on the voidability of treaties is full of passages from Grotius, Pufendorf, Vattel, and Wolff, all of whom he took to be authoritative expositors of the law of nations. But in lining up passages from each of the publicists, Jefferson suggested to the cabinet that one of these treatise writers should be differentiated from the others: Vattel’s views regarding the voidability of certain “disagreeable” alliances could not withstand the collective, contrary authority of the others." (Brian Richardson, “The Use of Vattel in the American Law of Nations,” *The American Journal of International Law* 106, no. 3 (2012): 558, doi:10.5305/amerjintelaw.106.3.0547.)
