- SecNav puts [William Bainbridge]() in charge of building a schooner at Baltimore on the exact specifications of the [USS *Enterprise*]() (21 March 1803, BW2:376)
- SecNav puts [Edward Preble]() in charge of building another brig at Portsmouth (23 March 1803, BW2:377)
- SecNav reports to [Richard Valentine Morris]() on 6 April 1803 that 3 schooners and 1 brig are being built and should be ready by August (BW2:387)
    - Originally meant to be built at Norfolk, Baltimore, Portsmouth, and Philadelphia, but SecNav scraps the Norfolk one and investigates the possibility of building at Boston instead (BW2:390, 13 April 1803)
    - 18 April 1803: SecNav also scraps Portsmouth vessel, instructed [Edward Preble]() rather to assist at Boston (BW2:393)
    - 25 April 1803: SecNav scraps plans to build at New York instead of Portsmouth (BW2:393)
- 28 April 1803: SecNav inquires about the possibility of buying the [*Nautilus*]() (BW2:394)
- 5 May 1803: SecNav buys the [*Nautilus*]() (BW2:397)
- Eventually two more ships built: Siren and Vixen